version: '3'
services:
  go:
    image: go
    container_name: go
    build:
      context: ./
      dockerfile: docker/go/Dockerfile
    volumes:
      - ././:/app
    tty: true
  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      - go
    ports:
      - 80:80
    links:
      - go
  mysql:
    image: mysql
    container_name: mysql
    build:
      context: ./
      dockerfile: docker/mysql/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: app
      MYSQL_USER: app_user
      MYSQL_PASSWORD: user_pass
  gocli:
    image: gocli
    container_name: gocli
    build:
      context: ./
      dockerfile: docker/gocli/Dockerfile
    volumes:
      - ./:/app
